name = "apoio"
main = ".worker/index.js"
compatibility_date = "2026-09-18"
workers_dev = true
preview_urls = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "portal-saude-db"
database_id = "4467670b-0e48-490a-8d56-fb4ad4cf6bce"

# Se Apoio e eMulti futuramente usarem subdomínios de um mesmo domínio
# personalizado, COOKIE_DOMAIN pode ser definido como variável do Worker.
# [vars]
# COOKIE_DOMAIN = ".seudominio.gov.br"
